export const ErrorMessages = {
  USER_ALREADY_EXISTS: 'User already exists',
  UNAUTHORIZED: 'Unauthorized',
  USER_NOT_FOUND: 'User not found',
  INVALID_INPUT: 'Invalid input data',
  SERVER_ERROR: 'Internal server error',
  INVALID_CREDINTIALS: 'Invalid Credintails',
  INVALID_OTP: 'Invalid OTP',
  INVALID_TOKEN: 'Invalid Token',
  UPDATE_FAILED: 'Update Failed',
  SUSPENDED_ACCOUNT: 'Your account has been suspended',
  INVALID_FILE_FORMAT: 'Invalid file format recieved',
  INVALID_FOLDER_TYPE: 'Invalid folder type',
  DOCUMENT_NOT_FOUND: 'Document not found',
  RIDE_NOT_FOUND: 'Ride not found',
  HIKE_NOT_FOUND: 'Hike not found',
  SEATS_NOT_AVAILABLE: 'Seats not available',
  HAS_PENDING_REQUESTS: 'You have already pending requests',
  JOINREQUEST_NOT_FOUND: 'No reqeuest available at the moment',
  ACCESS_DENIED: 'You dont have access for this action',
  PAYMENTINFO_NOT_FOUND: 'No payment info found',
} as const;
